-- ============================================================================
-- 03_STAGING.SQL — Generate synthetic data for Dealer Network & Sales Intelligence
-- Country: THAILAND | Currency: THB
-- ============================================================================
USE DATABASE DEALER_SALES_INTEL;
USE SCHEMA RAW;

-- Data generation scripts are demo-specific.
-- See the handcrafted SQL in the aws-malaysia-semiconductor-yield demo for
-- the full pattern: GENERATOR + UNIFORM + LATERAL for distribution,
-- Cortex Complete for text generation, engineered key demo numbers.

-- Target row counts:
-- DEALERS: 450 rows — Dealer locations across Thailand by region
-- SALES_TRANSACTIONS: 85,000 rows — 12 months of vehicle sales with customer and model details
-- CUSTOMER_PROFILES: 120,000 rows — Customer demographics, purchase history, service records
-- INVENTORY: 15,000 rows — Current dealer inventory by model, color, spec
-- LEADS: 35,000 rows — Sales leads with source, stage, and conversion status
-- NBA_ACTIONS: 2,000 rows — Next-best-action recommendations generated by AI
-- MARKETING_CAMPAIGNS: 200 rows — Campaign performance data by channel and region
-- THAI_AUTO_MARKET: 12 rows — Thailand automotive market size and competitive landscape
