-- Generated from generator/demo_specs/aws-thailand-automotive-dealer-sales.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-thailand-automotive-dealer-sales
-- This is the schema that is actually deployed for THAILAND_AUTOMOTIVE_DEALER_SALES.

-- Alerts fire on the bottom tail of Inventory Days
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_INVENTORY_DAYS) AS T
  FROM RAW.CUSTOMER_PROFILES
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_INVENTORY_DAYS <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_INVENTORY_DAYS), 2) AS AVG_INVENTORY_DAYS,
  ROUND(AVG(f.KPI_LEAD_CONVERSION), 2) AS AVG_LEAD_CONVERSION,
  ROUND(AVG(f.KPI_EV_MIX_FORECAST), 2) AS AVG_EV_MIX_FORECAST,
  ROUND(AVG(f.KPI_AVG_DAYS_TO_SALE), 2) AS AVG_DAYS_TO_SALE,
  ROUND(AVG(f.KPI_TEST_DRIVE_CONVERSION), 2) AS AVG_TEST_DRIVE_CONVERSION
FROM RAW.CUSTOMER_PROFILES f
JOIN RAW.THAI_AUTO_MARKET e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_INVENTORY_DAYS), 2) AS AVG_INVENTORY_DAYS,
  ROUND(AVG(f.KPI_LEAD_CONVERSION), 2) AS AVG_LEAD_CONVERSION,
  ROUND(AVG(f.KPI_EV_MIX_FORECAST), 2) AS AVG_EV_MIX_FORECAST,
  ROUND(AVG(f.KPI_AVG_DAYS_TO_SALE), 2) AS AVG_DAYS_TO_SALE,
  ROUND(AVG(f.KPI_TEST_DRIVE_CONVERSION), 2) AS AVG_TEST_DRIVE_CONVERSION
FROM RAW.CUSTOMER_PROFILES f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_INVENTORY_DAYS) AS KPI_INVENTORY_DAYS, AVG(KPI_LEAD_CONVERSION) AS KPI_LEAD_CONVERSION, AVG(KPI_EV_MIX_FORECAST) AS KPI_EV_MIX_FORECAST, AVG(KPI_AVG_DAYS_TO_SALE) AS KPI_AVG_DAYS_TO_SALE, AVG(KPI_TEST_DRIVE_CONVERSION) AS KPI_TEST_DRIVE_CONVERSION FROM RAW.CUSTOMER_PROFILES),
     en AS (SELECT SUM(KPI_DEALER_REVENUE_MTD) AS KPI_DEALER_REVENUE_MTD, SUM(KPI_ACTIVE_DEALERS) AS KPI_ACTIVE_DEALERS FROM RAW.THAI_AUTO_MARKET)
  SELECT 1 AS SORT_ORDER, 'Dealer Revenue (MTD)' AS TITLE, KPI_DEALER_REVENUE_MTD AS VALUE_NUM, '฿' || TO_VARCHAR(CAST(ROUND(((KPI_DEALER_REVENUE_MTD) / 1000000000), 1) AS DECIMAL(38,1))) || 'B' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Inventory Days' AS TITLE, KPI_INVENTORY_DAYS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_INVENTORY_DAYS)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Lead Conversion' AS TITLE, KPI_LEAD_CONVERSION AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_LEAD_CONVERSION), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Active Dealers' AS TITLE, KPI_ACTIVE_DEALERS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_ACTIVE_DEALERS)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'EV Mix Forecast' AS TITLE, KPI_EV_MIX_FORECAST AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_EV_MIX_FORECAST)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Avg Days to Sale' AS TITLE, KPI_AVG_DAYS_TO_SALE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_AVG_DAYS_TO_SALE)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Test Drive Conversion' AS TITLE, KPI_TEST_DRIVE_CONVERSION AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_TEST_DRIVE_CONVERSION)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
