-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Dealer Network & Sales Intelligence
-- ============================================================================
USE DATABASE DEALER_SALES_INTEL;
USE SCHEMA ML;

-- ML.FORECAST: REGIONAL_SALES_FORECAST
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.REGIONAL_SALES_FORECAST(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.REGIONAL_SALES_TRENDS'),
  SERIES_COLNAME => 'REGION_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y'
  
);

CREATE OR REPLACE TABLE ML.REGIONAL_SALES_FORECAST_RESULTS AS
SELECT * FROM TABLE(ML.REGIONAL_SALES_FORECAST!FORECAST(FORECASTING_PERIODS => 14));

-- ML.ANOMALY_DETECTION: DEALER_PERFORMANCE_ANOMALY
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.DEALER_PERFORMANCE_ANOMALY(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.DEALER_PERFORMANCE'),
  SERIES_COLNAME => 'DEALER_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.DEALER_PERFORMANCE_ANOMALY_RESULTS AS
SELECT * FROM TABLE(ML.DEALER_PERFORMANCE_ANOMALY!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.DEALER_PERFORMANCE'), SERIES_COLNAME => 'DEALER_ID', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'Y'));

