-- ============================================================================
-- 99_RESET.SQL — Reset Dealer Network & Sales Intelligence to clean demo state
-- ============================================================================
USE DATABASE DEALER_SALES_INTEL;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_GENERATE_NBA SUSPEND;
ALTER TASK IF EXISTS APP.TASK_SEND_OUTREACH SUSPEND;
ALTER TASK IF EXISTS APP.TASK_REFRESH_FORECASTS SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.DEALER_PERFORMANCE REFRESH;
ALTER DYNAMIC TABLE CURATED.REGIONAL_SALES_TRENDS REFRESH;
ALTER DYNAMIC TABLE CURATED.CUSTOMER_SEGMENTS REFRESH;
ALTER DYNAMIC TABLE CURATED.INVENTORY_DEMAND_MATCH REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM DEALER_SALES_INTEL.RAW.SALES_TRANSACTIONS → 85000
-- SELECT COUNT(*) FROM DEALER_SALES_INTEL.RAW.DEALERS → 450
-- SELECT COUNT(*) FROM DEALER_SALES_INTEL.CURATED.DEALER_PERFORMANCE WHERE SALES_VS_TARGET < 0.70 → ~47

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_REFRESH_FORECASTS RESUME;
ALTER TASK IF EXISTS APP.TASK_SEND_OUTREACH RESUME;
ALTER TASK IF EXISTS APP.TASK_GENERATE_NBA RESUME;
